[BitTorrent]
Session\DHTEnabled=false
Session\PeXEnabled=false
Session\LSDEnabled=false
Session\MaxConnections=2000
Session\MaxConnectionsPerTorrent=50
Session\Port=6881
Session\DefaultSavePath=/downloads
Session\TempPath=/downloads/incomplete
Session\TempPathEnabled=false
Session\QueueingSystemEnabled=false
Session\IgnoreSlowTorrentsForQueueing=true
Session\DisableAutoTMMByDefault=true
Session\AnonymousModeEnabled=false
Session\uTPRateLimited=false

[Preferences]
Connection\UPnP=false
Connection\PortRangeMin=6881
Downloads\SavePath=/downloads
Downloads\TempPath=/downloads/incomplete
Downloads\PreAllocation=false
Downloads\StartInPause=false
WebUI\Enabled=true
WebUI\Address=*
WebUI\Port=8080
WebUI\Username=ttb
WebUI\LocalHostAuth=false
WebUI\BypassLocalAuth=true
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\AuthSubnetWhitelist=127.0.0.1/8, ::1, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\HostHeaderValidation=false
Advanced\AnonymousMode=false
